sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  
jobs:
  include:
    - stage: MOM-Backend-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t mom_backend_flowz:"$DOCKER_IMAGE_TAG" ./server/
      - docker images
      - docker tag mom_backend_flowz:"$DOCKER_IMAGE_TAG" $DOCKER_USERNAME/mom_backend_flowz:"$DOCKER_IMAGE_TAG"
      - docker push $DOCKER_USERNAME/mom_backend_flowz:"$DOCKER_IMAGE_TAG"
    - stage: Upgrade Rancher Service 
      script: 
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh
    
