sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - demo

jobs:
  include:
    - stage: MOM-Backend-Flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "demo" ]; then
            echo "not build mom_backend_flowz image";
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t mom_backend_flowz:$TRAVIS_BRANCH ./server/;
            docker images;
            docker tag mom_backend_flowz:$TRAVIS_BRANCH $DOCKER_USERNAME/mom_backend_flowz:$TRAVIS_BRANCH;
            docker push $DOCKER_USERNAME/mom_backend_flowz:$TRAVIS_BRANCH;
        fi'    
    - stage: MOM-Frontend-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t mom_frontend_flowz:$TRAVIS_BRANCH --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="$AWS_SECRETKEY" ./client/
      - docker images
      - docker tag mom_frontend_flowz:$TRAVIS_BRANCH $DOCKER_USERNAME/mom_frontend_flowz:$TRAVIS_BRANCH
      - docker push $DOCKER_USERNAME/mom_frontend_flowz:$TRAVIS_BRANCH
    - stage: Upgrade Rancher Service
      script:
      - 'if [ ${TRAVIS_BRANCH} = "demo" ]; then
            bash ./upgrade_demo.sh;
         else
            bash ./upgrade.sh;
         fi'
    - stage: Finish Rancher Service
      script:
      - 'if [ ${TRAVIS_BRANCH} = "demo" ]; then
            bash ./finish_demo.sh;
         else
            bash ./finish.sh;
         fi'

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - uhirani@officebrain.com
      - igandhi@officebrain.com
    on_success: always
    on_failure: always
