default:
  service: sendmail
  code:
    success: 200
    error: 400
  message:
    success: Your Mail has been sent successfully
    error: Message sending failed
    valid_message: is not valid
    require_message: is required
  keys:
    blank: ""
    error: error
    success: success
